"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { createApplicationBootstrap } = require("./bootstrap");
function fakePersistence() { return { config: { provider: "sqlite", environment: "production" }, repositories: {}, driver: { dialect: { bind: (sql, params) => ({ sql, params }) }, close: async () => {} }, storage: { readAppliedMigrations: async () => [], ensureMigrationLedger: async () => {}, acquireLock: async () => {}, releaseLock: async () => {}, transaction: { run: async () => {} } } }; }
test("non-production bootstrap keeps the in-memory repository path", async () => { const result = await createApplicationBootstrap({ env: { ACME_ENV: "test" } }).start(); assert.equal(result.environment, "test"); assert.equal(result.persistence, null); const matter = await result.application.runtime.createMatter({ id: "m-1" }, { id: "u-1" }); assert.equal(matter.id, "m-1"); });
test("production bootstrap fails closed without an AI provider", async () => { await assert.rejects(() => createApplicationBootstrap({ env: { ACME_ENV: "production" }, productionPersistenceFactory: () => { throw new Error("should not be called"); } }).start(), /AI provider adapter|ACME_AI_PROVIDER_MODULE/); });
test("production bootstrap fails closed without an identity adapter", async () => { await assert.rejects(() => createApplicationBootstrap({ env: { ACME_ENV: "production", ACME_AI_PROVIDER_MODULE: "provider", ACME_OBJECT_STORAGE_MODULE: "storage" }, aiProviderFactory: () => ({ execute: async () => ({ answer: "draft" }) }), objectStorageFactory: () => ({ put: async () => {}, get: async () => {}, delete: async () => {} }), productionPersistenceFactory: () => { throw new Error("should not be called"); } }).start(), /ACME_AUTH_MODULE/); });
test("production bootstrap fails closed without object storage", async () => { await assert.rejects(() => createApplicationBootstrap({ env: { ACME_ENV: "production", ACME_OBJECT_STORAGE_MODULE: undefined }, provider: { execute: async () => ({ answer: "draft" }) }, authenticate: async () => ({ id: "u-1", role: "professional", human: true }), productionPersistenceFactory: () => { throw new Error("should not be called"); } }).start(), /ACME_OBJECT_STORAGE_MODULE/); });
test("production bootstrap runs migrations before exposing application and carries production adapters", async () => {
  const persistence = fakePersistence(); const authenticate = async () => ({ id: "u-1", role: "professional", human: true }); const provider = { id: "provider-1", execute: async () => ({ answer: "draft" }) }; const objectStorage = { put: async () => {}, get: async () => {}, delete: async () => {} }; const matterAuthorization = { assert: async () => true };
  const result = await createApplicationBootstrap({ env: { ACME_ENV: "production", ACME_DB_PROVIDER: "sqlite", ACME_DB_URL: "file:///tmp/acme-test.db", ACME_DB_SSL: "false" }, provider, authenticate, objectStorage, matterAuthorization, productionPersistenceFactory: () => persistence, applicationRuntimeFactory: ({ repositories, provider: wiredProvider, objectStorage: wiredStorage, matterAuthorization: wiredAuth }) => ({ repositories, provider: wiredProvider, objectStorage: wiredStorage, matterAuthorization: wiredAuth }), migrationManifest: { migrationTable: "acme_migrations", migrations: [] }, rootDir: process.cwd() }).start();
  assert.ok(result.migrationRunner); assert.equal(result.application.repositories, persistence.repositories); assert.equal(result.authenticate, authenticate); assert.equal(result.provider, provider); assert.equal(result.objectStorage, objectStorage); assert.equal(result.matterAuthorization, matterAuthorization); await result.close();
});
