"use strict";

const http = require("node:http");
const { URL } = require("node:url");
const { createStorageProvider } = require("./storage-provider");
const { createApplicationRuntime } = require("./application-runtime");
const { createApplicationBootstrap } = require("./bootstrap");
const { createHttpBoundary } = require("./http-boundary");
const { createPortalHttpBoundary } = require("./portal-http");
const { createPortalMatterHttpBoundary } = require("./portal-matter-http");

const MAX_BODY_BYTES = 64 * 1024;
const PUBLIC_ACTOR = Object.freeze({ id: "website-public-intake", type: "system", scope: "public-intake" });
const READ_OPERATIONS = new Set(["getClient", "getMatter", "getParty", "getRelationship", "getCheck", "getDocument", "getEvidence"]);
const OPERATIONS = Object.freeze({ "/api/consultations": { POST: ["submit"] }, "/api/clients": { POST: ["createClient"], GET: ["getClient"] }, "/api/matters": { POST: ["createMatter"], GET: ["getMatter"] }, "/api/parties": { POST: ["createParty"], GET: ["getParty"] }, "/api/relationships": { POST: ["createRelationship"], GET: ["getRelationship"] }, "/api/conflicts": { POST: ["checkMatter"], GET: ["getCheck"] }, "/api/documents": { POST: ["createDocument"], GET: ["getDocument"] }, "/api/evidence": { POST: ["createEvidence"], GET: ["getEvidence"] }, "/api/authorities": { POST: ["register"], GET: ["listByJurisdiction"] }, "/api/hearings": { POST: ["schedule"] }, "/api/diary": { POST: ["schedule"] }, "/api/sources": { POST: ["register", "verify"] }, "/api/legal-versions": { POST: ["create"] }, "/api/ai": { POST: ["execute"] }, "/api/ai/intake": { POST: ["execute"] }, "/api/ai/research": { POST: ["execute"] }, "/api/ai/review": { POST: ["execute"] }, "/api/reviews": { POST: ["create", "decide", "authorizeFinalAction"] }, "/api/partners": { POST: ["registerPartner", "verifyPartner"] }, "/api/billing": { POST: ["createInvoice", "issue", "recordPayment"] } });

function readJsonBody(request) { return new Promise((resolve, reject) => { let size = 0; let body = ""; let rejected = false; request.setEncoding("utf8"); request.on("data", (chunk) => { if (rejected) return; size += Buffer.byteLength(chunk); if (size > MAX_BODY_BYTES) { rejected = true; reject(Object.assign(new Error("Request body is too large"), { statusCode: 413 })); request.resume(); return; } body += chunk; }); request.on("end", () => { if (rejected) return; if (!body.trim()) return resolve({}); try { resolve(JSON.parse(body)); } catch { reject(Object.assign(new Error("Invalid JSON body"), { statusCode: 400 })); } }); request.on("error", reject); }); }
function json(response, statusCode, payload) { const body = JSON.stringify(payload); response.writeHead(statusCode, { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", "x-content-type-options": "nosniff", "content-length": Buffer.byteLength(body) }); response.end(body); }
function operationFor(path, method, input) { const choices = OPERATIONS[path]?.[method]; if (!choices?.length) throw Object.assign(new Error("Method not allowed"), { statusCode: 405 }); if (choices.length === 1) return choices[0]; if (!input?.operation || !choices.includes(input.operation)) throw Object.assign(new Error(`Operation is required; expected one of: ${choices.join(", ")}`), { statusCode: 400 }); return input.operation; }
async function invoke(service, operation, input, actor) { if (typeof service[operation] !== "function") throw Object.assign(new Error(`Service operation is not implemented: ${operation}`), { statusCode: 501 }); if (READ_OPERATIONS.has(operation)) return service[operation](input.id || input.recordId, actor); if (operation === "submit") return service.submit(input, actor); if (operation === "execute") return service.execute({ ...input, actor }); if (operation === "register" || operation === "create") return service[operation]({ ...input, actor }); if (operation === "verify") return service.verify(input.record || input, actor, input.verificationState); if (operation === "registerPartner") return service.registerPartner({ ...input, actor }); if (operation === "verifyPartner") return service.verifyPartner(input.partner || input, actor, input.verificationState, input.evidence || []); if (operation === "schedule") return service.schedule({ ...input, actor }); if (["createClient", "createMatter", "createParty", "createRelationship", "checkMatter", "createDocument", "createEvidence"].includes(operation)) return service[operation](input, actor); if (operation === "createInvoice") return service.createInvoice({ ...input, actor }); if (operation === "issue") return service.issue(input.invoice || input, actor); if (operation === "recordPayment") return service.recordPayment({ ...input, actor }); if (operation === "decide") return service.decide(input.review || input, input.decision, actor, input.modification ?? null); if (operation === "authorizeFinalAction") return service.authorizeFinalAction(input.review || input, input.action, actor); if (operation === "listByJurisdiction") return service.listByJurisdiction(input.jurisdiction); throw Object.assign(new Error(`Unsupported service operation: ${operation}`), { statusCode: 501 }); }
function resolveHttpApplication(application) { if (!application?.application) return application; const runtime = application.application; const crm = application.crmOperations ? Object.freeze({ ...runtime.crm, createClient: (input, actor) => application.crmOperations.createClient({ client: input, actor }), createMatter: (input, actor) => application.crmOperations.createMatter({ matter: input, actor }) }) : runtime.crm; if (!application.matterDomainOperations) return Object.freeze({ ...runtime, crm }); const domain = application.matterDomainOperations; return Object.freeze({ ...runtime, crm, party: Object.freeze({ ...runtime.party, createParty: (input, actor) => domain.addParty({ actor, matterId: input.matterId, party: input }) }), relationship: Object.freeze({ ...runtime.relationship, createRelationship: (input, actor) => domain.addRelationship({ actor, matterId: input.matterId, relationship: input }) }), conflict: Object.freeze({ ...runtime.conflict, checkMatter: (input, actor) => domain.recordConflictCheck({ actor, matterId: input.matterId, conflict: input }) }), document: Object.freeze({ ...runtime.document, createDocument: (input, actor) => domain.addDocument({ actor, matterId: input.matterId, document: input }) }), evidence: Object.freeze({ ...runtime.evidence, createEvidence: (input, actor) => domain.addEvidence({ actor, matterId: input.matterId, evidence: input }) }) }); }
function createHttpServer({ application, repositories, authenticate = async () => null, publicActor = PUBLIC_ACTOR } = {}) { const storage = createStorageProvider({ repositories }); const runtime = resolveHttpApplication(application || createApplicationRuntime({ repositories: storage.repositories, provider: { execute: async () => ({ answer: "draft" }) } })); const boundary = createHttpBoundary({ application: runtime, authenticate, publicActor }); const portalBoundary = createPortalHttpBoundary({ portal: runtime.portal, authenticate }); const portalMatterBoundary = createPortalMatterHttpBoundary({ portalMatter: runtime.portalMatter, authenticate }); return http.createServer(async (request, response) => { try { if (request.method === "OPTIONS") { response.writeHead(204, { "access-control-allow-methods": "POST,GET,OPTIONS", "access-control-allow-headers": "content-type,authorization" }); return response.end(); } const url = new URL(request.url, "http://localhost"); if (url.pathname === "/health") return json(response, 200, { status: "ok", persistence: "provider-boundary" }); if (Object.prototype.hasOwnProperty.call(portalBoundary.routes, url.pathname)) return json(response, 200, await portalBoundary.dispatch(request)); if (Object.prototype.hasOwnProperty.call(portalMatterBoundary.routes, url.pathname)) { const body = request.method === "GET" ? {} : await (String(request.headers["content-type"] || "").toLowerCase().includes("application/json") ? readJsonBody(request) : Promise.reject(Object.assign(new Error("Content-Type must be application/json"), { statusCode: 415 }))); return json(response, 200, await portalMatterBoundary.dispatch(request, body)); } if (!Object.prototype.hasOwnProperty.call(boundary.routes, url.pathname)) return json(response, 404, { error: "Not found" }); const input = request.method === "GET" ? Object.fromEntries(url.searchParams.entries()) : await (String(request.headers["content-type"] || "").toLowerCase().includes("application/json") ? readJsonBody(request) : Promise.reject(Object.assign(new Error("Content-Type must be application/json"), { statusCode: 415 }))); const resolved = await boundary.resolve(url.pathname, request); const operation = operationFor(url.pathname, request.method, input); return json(response, 200, await invoke(resolved.service, operation, input, resolved.actor)); } catch (error) { const status = Number.isInteger(error.statusCode) ? error.statusCode : error.code === "MATTER_ACCESS_DENIED" ? 403 : /Authenticated actor is required|identity is required|access denied|Authorized human professional is required/i.test(error.message || "") ? (error.code === "MATTER_ACCESS_DENIED" || /access denied/i.test(error.message || "") ? 403 : 401) : /Invalid|incomplete/i.test(error.message || "") ? 400 : 500; return json(response, status, { error: error.message || "Internal server error" }); } }); }

if (require.main === module) { const port = Number(process.env.PORT || 3000); const bootstrap = createApplicationBootstrap(); bootstrap.start().then((application) => { const server = createHttpServer({ application }); server.on("close", () => application.close().catch(() => {})); server.listen(port, () => console.log(`ACME API listening on ${port} (${application.environment})`)); }).catch((error) => { console.error(`ACME startup failed: ${error.message}`); process.exitCode = 1; }); }
module.exports = { MAX_BODY_BYTES, OPERATIONS, PUBLIC_ACTOR, createHttpServer, invoke, operationFor, readJsonBody, resolveHttpApplication };
