const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const API='/api', INDIA='https://indiacode.ecourtsindia.com/api/v1';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const docs={privacy:{title:'Privacy Policy',body:'<p>Information voluntarily submitted through this website may be used to operate requested services, respond to enquiries, support public-source research and route professional intake where applicable.</p><h3>Important</h3><p>Do not submit passwords, payment credentials or information you are not authorized to disclose through public forms.</p>'},cookies:{title:'Cookie Policy',body:'<p>ACME uses necessary browser storage for core operation and optional analytics only when enabled by the visitor.</p>'},terms:{title:'Terms & Conditions',body:'<p>Website content and public research are informational. Use of the website does not by itself establish a professional-client relationship or constitute final legal, tax, accounting, regulatory or business advice.</p>'},disclosure:{title:'Full Disclosure',body:'<p>Technology is an assistive layer. Public-source research may be incomplete, outdated or jurisdictionally inapplicable. Professional review remains necessary before final action.</p>'}};
function cookieGet(n){return document.cookie.split('; ').find(x=>x.startsWith(n+'='))?.split('=').slice(1).join('=')}
function cookieSet(n,v){document.cookie=n+'='+encodeURIComponent(v)+'; Max-Age=31536000; Path=/; SameSite=Lax'+(location.protocol==='https:'?'; Secure':'')}
function openLegal(k){const d=docs[k];if(!d)return;const m=document.createElement('div');m.className='modal-backdrop';m.innerHTML='<section class="modal" role="dialog" aria-modal="true"><button class="modal-close" aria-label="Close">×</button><p class="mono gold">ACME / WEBSITE NOTICE</p><h2>'+d.title+'</h2>'+d.body+'</section>';document.body.append(m);document.body.classList.add('lock');$('.modal-close',m).focus();$('.modal-close',m).onclick=()=>{m.remove();document.body.classList.remove('lock')};m.onclick=e=>{if(e.target===m){m.remove();document.body.classList.remove('lock')}}}
function openAsk(seed=''){const p=$('.ask-panel');p?.classList.add('open');if(seed&&p)$('#ask-query',p).value=seed;setTimeout(()=>$('#ask-query',p)?.focus(),180)}
function closeAsk(){$('.ask-panel')?.classList.remove('open')}
function renderResults(data){const rows=Array.isArray(data.results)?data.results:[];return '<div class="mono gold">RESEARCH OUTPUT / '+esc(data.source||'PUBLIC SOURCE')+' · '+rows.length+' RESULTS</div>'+rows.map((r,i)=>'<article class="result"><small>#'+(i+1)+' · '+esc(r.source||data.source||'Public source')+'</small><h4>'+esc(r.title||r.name||r.act||'Legal authority')+'</h4>'+(r.section?'<p>Section '+esc(r.section)+'</p>':'')+(r.snippet?'<p>'+esc(r.snippet)+'</p>':'')+(r.url?'<a href="'+esc(r.url)+'" target="_blank" rel="noopener noreferrer">OPEN SOURCE ↗</a>':'')+'</article>').join('')+'<p class="mono" style="color:#718088;line-height:1.6">Public-source retrieval only. Verify authority, current legal state and application with a qualified professional.</p>'}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function research(q){try{const r=await fetch(API+'/legal-research?q='+encodeURIComponent(q)+'&limit=6',{headers:{Accept:'application/json'},credentials:'same-origin'});if(r.ok)return r.json()}catch{}const r=await fetch(INDIA+'/search?q='+encodeURIComponent(q)+'&limit=6',{headers:{Accept:'application/json'}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||'Public legal research is temporarily unavailable.');return{source:'India Code',results:(b.results||[]).map(x=>({...x,source:'India Code'}))}}
async function submitAsk(e){e.preventDefault();const f=e.currentTarget,q=$('#ask-query',f).value.trim(),j=$('#ask-jurisdiction',f).value,s=$('.ask-status',f),out=$('.results',f),b=$('.ask-send',f);if(!q){s.textContent='Enter a question first.';return}b.disabled=true;s.textContent='Researching public sources…';out.innerHTML='';try{const d=await research(q+' in '+j);out.innerHTML=renderResults(d);s.textContent='Research complete.';out.scrollTop=0}catch(err){s.textContent=err.message||'Research could not be completed.'}finally{b.disabled=false}}
function openConsultation(){const m=document.createElement('div');m.className='modal-backdrop';m.innerHTML='<section class="modal" role="dialog" aria-modal="true"><button class="modal-close" aria-label="Close">×</button><p class="mono gold">ACME / PROFESSIONAL CONSULTATION</p><h2>Bring the matter.</h2><p>Share the essential facts. This is an intake request, not a final legal opinion.</p><form class="form-grid" id="consult-form"><label>Name<input name="name" required autocomplete="name"></label><label>Email<input name="email" type="email" required autocomplete="email"></label><label>Phone<input name="phone" type="tel"></label><label>Jurisdiction<input name="jurisdiction" placeholder="India / Maharashtra"></label><label class="full">Subject<input name="subject" required></label><label class="full">Matter summary<textarea name="summary" required></textarea></label><button class="btn full" type="submit">Submit request →</button><p class="form-status full"></p></form></section>';document.body.append(m);document.body.classList.add('lock');$('.modal-close',m).onclick=()=>{m.remove();document.body.classList.remove('lock')};m.onclick=e=>{if(e.target===m){m.remove();document.body.classList.remove('lock')}};$('#consult-form',m).onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,s=$('.form-status',f),b=$('button[type=submit]',f),data=Object.fromEntries(new FormData(f));b.disabled=true;s.textContent='Submitting securely…';try{const r=await fetch(API+'/consultations',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(data)}),x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x.error||'Submission failed.');s.textContent=x.message||'Your request has been received.';f.reset()}catch(err){s.textContent=err.message}finally{b.disabled=false}}}
function consent(){if(cookieGet('acme_consent'))return;const m=document.createElement('div');m.className='modal-backdrop';m.innerHTML='<section class="modal" role="dialog" aria-modal="true"><p class="mono gold">ACME / WEBSITE DISCLAIMER</p><h2>Enter with clarity.</h2><p>Information on this website is for general purposes. Public research does not constitute legal, tax, accounting, regulatory or business advice.</p><button class="btn" id="continue">I Understand — Continue →</button></section>';document.body.append(m);document.body.classList.add('lock');$('#continue',m).onclick=()=>{cookieSet('acme_consent','necessary');m.remove();document.body.classList.remove('lock')}}
function initCursor(){if(matchMedia('(pointer:fine)').matches)document.body.classList.add('has-cursor')}
addEventListener('DOMContentLoaded',()=>{
  initCursor();consent();
  const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});
  $$('.reveal').forEach(e=>io.observe(e));
  const header=$('.acme-header'),progress=$('.progress');
  addEventListener('scroll',()=>{header?.classList.toggle('scrolled',scrollY>30);const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(max>0?scrollY/max*100:0)+'%'},{passive:true});
  const menu=$('.menu'),nav=$('.nav');
  menu?.addEventListener('click',()=>{const open=nav?.classList.toggle('open');menu.setAttribute('aria-expanded',String(!!open))});
  $$('.nav a').forEach(a=>a.addEventListener('click',()=>{nav?.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
  $$('[data-ask]').forEach(b=>b.addEventListener('click',()=>openAsk(b.dataset.ask||'')));
  $('.ask-close')?.addEventListener('click',closeAsk);
  $('.ask-form')?.addEventListener('submit',submitAsk);
  $$('.ask-chip').forEach(b=>b.addEventListener('click',()=>openAsk(b.textContent)));
  $$('[data-consult]').forEach(b=>b.addEventListener('click',openConsultation));
  $$('[data-legal]').forEach(b=>b.addEventListener('click',()=>openLegal(b.dataset.legal)));
  $$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll)?.scrollIntoView({behavior:reduced?'auto':'smooth'})));
  addEventListener('keydown',e=>{if(e.key==='Escape'){closeAsk();$('.modal-backdrop')?.remove();document.body.classList.remove('lock');nav?.classList.remove('open');menu?.setAttribute('aria-expanded','false')}});
});
