const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const API_BASE='/api';
addEventListener('load',()=>setTimeout(()=>$('.loader')?.classList.add('done'),350));
const header=$('[data-header]'),progress=$('[data-progress]');
addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=`${max>0?(scrollY/max)*100:0}%`;header?.classList.toggle('scrolled',scrollY>40)},{passive:true});
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12});
$$('.reveal').forEach((el,i)=>{if(!reduced)el.style.transitionDelay=`${Math.min(i%5,4)*60}ms`;io.observe(el)});
const world=$('[data-world]');if(world&&!reduced){const wo=new IntersectionObserver(e=>{if(e[0].isIntersecting){world.classList.add('is-active');wo.disconnect()}},{threshold:.25});wo.observe(world)}
const toggle=$('.menu-toggle'),nav=$('.site-nav');toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});$$('.site-nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}));
$$('.node').forEach(n=>n.addEventListener('click',()=>{world?.setAttribute('aria-label',`${n.dataset.node} selected`);$$('.node').forEach(x=>x.removeAttribute('aria-current'));n.setAttribute('aria-current','true')}));
if(!reduced&&matchMedia('(pointer:fine)').matches){addEventListener('pointermove',e=>{const x=(e.clientX/innerWidth-.5)*10,y=(e.clientY/innerHeight-.5)*10;world?.style.setProperty('--mx',`${x}px`);world?.style.setProperty('--my',`${y}px`)},{passive:true})}

async function submitConsultation(payload){const response=await fetch(`${API_BASE}/consultations`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(payload)});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Consultation request could not be submitted. Please check your details and try again.');return body;}

function validateForm(form){let valid=true;form.querySelectorAll('[required]').forEach(field=>{const bad=!field.value.trim()||(field.type==='email'&&!/^\S+@\S+\.\S+$/.test(field.value));field.setAttribute('aria-invalid',bad?'true':'false');if(bad)valid=false});return valid}

function openAskAcme(){
  if($('.ask-acme-modal'))return $('.ask-acme-modal textarea')?.focus();
  const modal=document.createElement('div');modal.className='ask-acme-modal';modal.innerHTML=`<div class="ask-acme-panel" role="dialog" aria-modal="true" aria-labelledby="ask-acme-title"><button class="ask-acme-close" type="button" aria-label="Close Ask ACME">×</button><p class="eyebrow dark">ACME / ASK ACME</p><h2 id="ask-acme-title">Start with the <em>question.</em></h2><p>Give ACME the facts you are comfortable sharing, identify the jurisdiction, and describe what you need help with. This public intake routes the request for professional review; it does not provide a final legal opinion.</p><form class="ask-acme-form" data-ask-form novalidate><label>What do you need help with?<textarea name="summary" rows="6" required placeholder="Describe the issue, decision, document, transaction or question…"></textarea></label><label>Jurisdiction<input name="jurisdiction" placeholder="e.g. India, Hong Kong, UAE"></label><label>Urgency<select name="urgency"><option value="standard">Standard</option><option value="urgent">Urgent</option><option value="critical">Critical</option></select></label><label>Your email<input name="email" type="email" autocomplete="email" required placeholder="name@example.com"></label><div class="ask-acme-actions"><button class="button button-gold ask-acme-submit" type="submit">Send to ACME <span>↗</span></button><button class="text-link" type="button" data-ask-cancel>Cancel</button></div><p class="ask-acme-status" data-ask-status role="status" aria-live="polite"></p><p class="ask-acme-hint">Avoid sending passwords, payment credentials or highly sensitive documents through this public intake.</p></form></div>`;document.body.append(modal);
  const form=$('[data-ask-form]',modal),status=$('[data-ask-status]',modal),button=$('.ask-acme-submit',modal);const close=()=>modal.remove();$('.ask-acme-close',modal).addEventListener('click',close);$('[data-ask-cancel]',modal).addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});
  form.querySelectorAll('input,textarea,select').forEach(field=>field.addEventListener('input',()=>field.setAttribute('aria-invalid','false')));
  form.addEventListener('submit',async e=>{e.preventDefault();status.dataset.state='';status.textContent='';if(!validateForm(form)){status.dataset.state='error';status.textContent='Please complete the required fields and enter a valid email address.';form.querySelector('[aria-invalid="true"]')?.focus();return}const data=Object.fromEntries(new FormData(form).entries());button.disabled=true;status.dataset.state='busy';status.textContent='Submitting securely…';try{const result=await submitConsultation({name:data.email, email:data.email, subject:`ASK ACME — ${data.jurisdiction||'Jurisdiction to be confirmed'}`, jurisdiction:data.jurisdiction, urgency:data.urgency, summary:data.summary});form.reset();form.querySelectorAll('[aria-invalid]').forEach(f=>f.setAttribute('aria-invalid','false'));status.dataset.state='success';status.textContent=result.message||'Your Ask ACME request has been received. A professional workflow will follow.'}catch(error){status.dataset.state='error';status.textContent=error.message}finally{button.disabled=false}});
  $('[name="summary"]',modal)?.focus();
}

function openConsultation(){
  if($('.consultation-modal'))return $('.consultation-modal input')?.focus();
  const modal=document.createElement('div');modal.className='consultation-modal';modal.innerHTML=`<div class="consultation-panel" role="dialog" aria-modal="true" aria-labelledby="consultation-title"><button class="consultation-close" type="button" aria-label="Close consultation">×</button><p class="eyebrow">ACME / CONSULTATION</p><h2 id="consultation-title">Bring ACME <em>the matter.</em></h2><p>Share the essential facts. This is an intake request, not a final legal opinion.</p><form data-consultation-form novalidate><label>Name<input name="name" autocomplete="name" required></label><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Phone<input name="phone" type="tel" autocomplete="tel"></label><label>Subject<input name="subject" required></label><label>Jurisdiction<input name="jurisdiction" placeholder="e.g. India, Hong Kong"></label><label>Urgency<select name="urgency"><option value="standard">Standard</option><option value="urgent">Urgent</option><option value="critical">Critical</option></select></label><label>Matter summary<textarea name="summary" rows="5" required></textarea></label><button class="button button-gold" type="submit">Submit consultation <span>↗</span></button><p class="form-status" data-form-status role="status" aria-live="polite"></p></form></div>`;document.body.append(modal);
  const form=$('[data-consultation-form]',modal),status=$('[data-form-status]',form),button=form.querySelector('button[type="submit"]'),close=()=>modal.remove();$('.consultation-close',modal).addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});
  form.querySelectorAll('input,textarea,select').forEach(field=>field.addEventListener('input',()=>field.setAttribute('aria-invalid','false')));
  form.addEventListener('submit',async e=>{e.preventDefault();status.dataset.state='';status.textContent='';if(!validateForm(form)){status.dataset.state='error';status.textContent='Please complete the required fields and check your email address.';form.querySelector('[aria-invalid="true"]')?.focus();return}const data=Object.fromEntries(new FormData(form).entries());button.disabled=true;status.dataset.state='busy';status.textContent='Submitting securely…';try{const result=await submitConsultation(data);form.reset();status.dataset.state='success';status.textContent=result.message||'Your consultation request has been received.'}catch(error){status.dataset.state='error';status.textContent=error.message}finally{button.disabled=false}});
  $('.consultation-modal input',modal)?.focus();
}
$$('[data-ask-acme]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openAskAcme()}));
$$('a[href^="mailto:"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openConsultation()}));
$$('.floating a[href="#consultation"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openConsultation()}));
