const $=(s,c=document)=>c.querySelector(s);
const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const API_BASE='/api';
const INDIA_CODE_API='https://indiacode.ecourtsindia.com/api/v1';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
document.documentElement.classList.add('js');
function setCookie(name,value,days=365){const secure=location.protocol==='https:'?'; Secure':'';document.cookie=`${name}=${encodeURIComponent(value)}; Max-Age=${days*86400}; Path=/; SameSite=Lax${secure}`}
function getCookie(name){const found=document.cookie.split('; ').find(row=>row.startsWith(`${name}=`));return found?decodeURIComponent(found.split('=').slice(1).join('=')):null}
const legalDocuments={
 cookies:{title:'Cookie Policy',html:`<p>This website uses cookies or similar browser storage only for functions needed to operate the site and, where enabled by you, for optional analytics.</p><h3>Necessary technologies</h3><p>These support core functions such as consent state, interface preferences and security-related operation. They cannot be switched off through this preference control.</p><h3>Optional analytics</h3><p>Optional analytics are disabled unless you choose them in the consent gateway. No analytics script is enabled by this frontend without that choice.</p><h3>Your choice</h3><p>You can change the optional analytics choice at any time using “Cookie preferences” in the footer. Clearing browser storage may reset your preference.</p>`},
 privacy:{title:'Privacy Policy',html:`<p>This website may receive information that you voluntarily submit through public forms, including consultation and AskACME research requests.</p><h3>Use of submitted information</h3><p>Information is used to operate the requested service, respond to enquiries, support research retrieval and route professional intake where applicable. Do not submit passwords, payment credentials or information that you are not authorized to disclose.</p><h3>Public research</h3><p>AskACME may query public legal sources. The research result is an orientation layer and should be independently verified before reliance or action.</p><h3>Third-party services</h3><p>Where this site connects to external services, their own terms and privacy practices may also apply. The website does not claim control over information processed by independent third parties.</p>`},
 terms:{title:'Terms & Conditions',html:`<p>By using this website, you agree to use it lawfully and not to interfere with its operation, security or availability.</p><h3>Informational website</h3><p>Website content is provided for general information and does not, by itself, establish a professional-client relationship or constitute a final legal, tax, accounting, regulatory or business opinion.</p><h3>AskACME</h3><p>AskACME provides public-source research and structured orientation. Its output must not be treated as autonomous professional advice. Facts, jurisdiction, effective law and professional review may materially change the appropriate conclusion.</p><h3>Accuracy and availability</h3><p>ACME seeks useful and source-conscious information but does not warrant that every public source, index, result or external service is complete, current or uninterrupted.</p><h3>Prohibited use</h3><p>You must not use the site to submit malicious code, attempt unauthorized access, impersonate another person, or knowingly provide information you have no right to disclose.</p>`},
 disclosure:{title:'Full Disclosure',html:`<p>ACME uses technology as an assistive layer within a professional-services workflow.</p><h3>Human review</h3><p>Professional review remains the governing step for final legal, regulatory, tax, accounting or commercial action. Website research does not replace that review.</p><h3>Sources and jurisdiction</h3><p>Public-source results may be affected by source availability, indexing, amendments, effective dates, jurisdiction and the completeness of the question submitted.</p><h3>No automatic professional relationship</h3><p>Submitting a website question or form does not by itself create a solicitor-client, attorney-client, accountant-client, tax adviser-client or other professional relationship.</p><h3>Confidentiality warning</h3><p>Do not submit passwords, payment credentials, highly sensitive personal information, trade secrets or confidential documents through the public AskACME intake unless an authorized secure channel has specifically been provided.</p>`}
};
function showLegal(key){const drawer=$('[data-legal-drawer]'),title=$('[data-legal-title]',drawer),content=$('[data-legal-content]',drawer),doc=legalDocuments[key];if(!doc)return;title.textContent=doc.title;content.innerHTML=doc.html;drawer.hidden=false;document.body.classList.add('is-locked');$('[data-legal-close]',drawer)?.focus()}
function closeLegal(){const drawer=$('[data-legal-drawer]');if(!drawer)return;drawer.hidden=true;document.body.classList.remove('is-locked')}
function revealSite(){const site=$('[data-site]'),gateway=$('[data-consent-gateway]');site.hidden=false;gateway.hidden=true;document.body.classList.remove('is-locked');if(!reduced)requestAnimationFrame(()=>$$('.reveal').forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i%5,4)*55}ms`;io.observe(el)}))}
function saveConsent(analytics){setCookie('acme_consent',analytics?'analytics':'necessary');try{localStorage.setItem('acme_consent',analytics?'analytics':'necessary')}catch{}revealSite()}
function initConsent(){const stored=getCookie('acme_consent');if(stored==='necessary'||stored==='analytics'){revealSite();return}setTimeout(()=>{$('[data-consent-gateway]').hidden=false;document.body.classList.add('is-locked')},reduced?0:900)}
function resetConsent(){document.cookie='acme_consent=; Max-Age=0; Path=/; SameSite=Lax';try{localStorage.removeItem('acme_consent')}catch{}location.reload()}
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12});
function focusAsk(text=''){const input=$('#ask-query');document.querySelector('#ask-acme')?.scrollIntoView({behavior:reduced?'auto':'smooth',block:'center'});setTimeout(()=>{if(text)input.value=text;input?.focus()},reduced?0:450)}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function researchLegalQuery(query){try{const response=await fetch(`${API_BASE}/legal-research?q=${encodeURIComponent(query)}&limit=6`,{headers:{Accept:'application/json'},credentials:'same-origin'});if(response.ok)return await response.json()}catch{}const response=await fetch(`${INDIA_CODE_API}/search?q=${encodeURIComponent(query)}&limit=6`,{headers:{Accept:'application/json'}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'The public legal research source is temporarily unavailable.');return{query,source:'India Code',classification:{jurisdiction:'India'},results:(body.results||[]).map(r=>({...r,source:'India Code',sourceType:'public_primary',verification:'source_returned'})),disclaimer:'Public-source retrieval only. Verify the authority, current legal state and application with a qualified professional.'}}
function renderResearch(result,box){const rows=Array.isArray(result.results)?result.results:[];box.innerHTML=`<div class="ask-results-head"><span>RESEARCH OUTPUT / ${escapeHtml(result.source||'PUBLIC SOURCE')}</span><b>${rows.length} source${rows.length===1?'':'s'}</b></div>${rows.length?`<div class="ask-results-list">${rows.map((r,i)=>`<article class="ask-result"><div><small>#${i+1} · ${escapeHtml(r.source||result.source||'Public source')}</small><h3>${escapeHtml(r.title||r.name||r.act||'Legal authority')}</h3>${r.section?`<p>Section ${escapeHtml(r.section)}</p>`:''}${r.snippet?`<p>${escapeHtml(r.snippet)}</p>`:''}</div>${r.url?`<a href="${escapeHtml(r.url)}" target="_blank" rel="noopener noreferrer">SOURCE ↗</a>`:''}</article>`).join('')}</div>`:`<p class="ask-results-empty">No matching public source was returned. Refine the facts, jurisdiction or section and try again.</p>`}<p class="ask-results-note">${escapeHtml(result.disclaimer||'Public-source retrieval only. Verify the authority, current legal state and application with a qualified professional.')}</p>`;box.hidden=false}
async function handleAskSubmit(form){const status=$('[data-ask-status]'),button=$('.ask-submit',form),results=$('[data-ask-results]'),data=Object.fromEntries(new FormData(form).entries());if(!data.summary.trim()){status.dataset.state='error';status.textContent='Please enter the question you want ACME to research.';$('#ask-query')?.focus();return}const query=[data.summary,data.jurisdiction].filter(Boolean).join(' in ');button.disabled=true;status.dataset.state='busy';status.textContent='Researching public sources…';results.hidden=true;try{const result=await researchLegalQuery(query);renderResearch(result,results);status.dataset.state='success';status.textContent='Research complete.';results.scrollIntoView({behavior:reduced?'auto':'smooth',block:'nearest'})}catch(error){status.dataset.state='error';status.textContent=error.message||'Research could not be completed.'}finally{button.disabled=false}}
function openConsultation(){if($('.consultation-modal'))return;const modal=document.createElement('div');modal.className='consultation-modal';modal.innerHTML=`<div class="consultation-panel" role="dialog" aria-modal="true" aria-labelledby="consultation-title"><button class="consultation-close" type="button" aria-label="Close consultation">×</button><p class="eyebrow dark">ACME / CONSULTATION</p><h2 id="consultation-title">Bring ACME <em>the matter.</em></h2><p>Share the essential facts. This is an intake request, not a final legal opinion.</p><form data-consultation-form novalidate><label>Name<input name="name" autocomplete="name" required></label><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Phone<input name="phone" type="tel" autocomplete="tel"></label><label>Subject<input name="subject" required></label><label>Jurisdiction<input name="jurisdiction" placeholder="e.g. India, Maharashtra"></label><label>Urgency<select name="urgency"><option value="standard">Standard</option><option value="urgent">Urgent</option><option value="critical">Critical</option></select></label><label>Matter summary<textarea name="summary" rows="5" required></textarea></label><button class="button button-gold" type="submit">Submit consultation <span>→</span></button><p class="form-status" data-form-status role="status" aria-live="polite"></p></form></div>`;document.body.append(modal);const form=$('[data-consultation-form]',modal),status=$('[data-form-status]',modal),submit=$('button[type=submit]',form);const close=()=>{modal.remove();document.body.classList.remove('is-locked')};$('.consultation-close',modal).addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.body.classList.add('is-locked');form.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries()),invalid=[...form.querySelectorAll('[required]')].find(x=>!x.value.trim()||(x.type==='email'&&!/^\S+@\S+\.\S+$/.test(x.value)));if(invalid){invalid.setAttribute('aria-invalid','true');status.dataset.state='error';status.textContent='Please complete the required fields.';invalid.focus();return}submit.disabled=true;status.dataset.state='busy';status.textContent='Submitting securely…';try{const response=await fetch(`${API_BASE}/consultations`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(data)}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Consultation request could not be submitted.');form.reset();status.dataset.state='success';status.textContent=body.message||'Your consultation request has been received.'}catch(error){status.dataset.state='error';status.textContent=error.message}finally{submit.disabled=false}});$('input',form)?.focus()}
addEventListener('load',()=>{const loader=$('[data-loader]');if(loader)setTimeout(()=>loader.classList.add('done'),reduced?0:300);initConsent();const header=$('[data-header]'),progress=$('[data-progress]');addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=`${max>0?(scrollY/max)*100:0}%`;header?.classList.toggle('scrolled',scrollY>40)},{passive:true});$('.menu-toggle')?.addEventListener('click',()=>{const nav=$('#site-nav'),toggle=$('.menu-toggle'),open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});$$('.site-nav a').forEach(a=>a.addEventListener('click',()=>{$('#site-nav')?.classList.remove('open');$('.menu-toggle')?.setAttribute('aria-expanded','false')}));$$('[data-focus-ask]').forEach(btn=>btn.addEventListener('click',()=>focusAsk()));$$('[data-suggestion]').forEach(btn=>btn.addEventListener('click',()=>focusAsk(btn.dataset.suggestion||'')));$$('[data-ask-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();handleAskSubmit(form)}));$$('[data-legal]').forEach(btn=>btn.addEventListener('click',()=>showLegal(btn.dataset.legal)));$('[data-legal-close]')?.addEventListener('click',closeLegal);$('[data-legal-drawer]')?.addEventListener('click',e=>{if(e.target===e.currentTarget)closeLegal()});$('[data-consent-accept]')?.addEventListener('click',()=>saveConsent(true));$('[data-consent-preferences]')?.addEventListener('click',()=>saveConsent($('[data-consent-analytics]')?.checked===true));$('[data-consent-reset]')?.addEventListener('click',resetConsent);$$('[data-consultation]').forEach(btn=>btn.addEventListener('click',openConsultation));addEventListener('keydown',e=>{if(e.key==='Escape'){closeLegal();document.querySelector('.consultation-modal')?.remove();document.body.classList.remove('is-locked')}});if(!reduced)requestAnimationFrame(()=>$$('.reveal').forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i%5,4)*55}ms`;io.observe(el)}))});
