const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const API='/api',INDIA='https://indiacode.ecourtsindia.com/api/v1';
const docs={privacy:'Privacy Policy',cookies:'Cookie Policy',terms:'Terms & Conditions',disclosure:'Full Disclosure'};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openAsk(seed=''){const p=$('.ask-panel');p.classList.add('open');if(seed)$('#ask-query').value=seed;setTimeout(()=>$('#ask-query').focus(),120)}
function closeAsk(){$('.ask-panel')?.classList.remove('open')}
async function research(q){try{const r=await fetch(API+'/legal-research?q='+encodeURIComponent(q)+'&limit=6',{headers:{Accept:'application/json'},credentials:'same-origin'});if(r.ok)return r.json()}catch{}const r=await fetch(INDIA+'/search?q='+encodeURIComponent(q)+'&limit=6',{headers:{Accept:'application/json'}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||'Public legal research is temporarily unavailable.');return{source:'India Code',results:(b.results||[]).map(x=>({...x,source:'India Code'}))}}
function renderResults(d){const rows=Array.isArray(d.results)?d.results:[];return '<div class="result-label">PUBLIC RESEARCH / '+esc(d.source||'SOURCE')+' · '+rows.length+' RESULTS</div>'+rows.map((r,i)=>'<article class="result"><small>#'+(i+1)+' · '+esc(r.source||d.source||'Public source')+'</small><h4>'+esc(r.title||r.name||r.act||'Legal authority')+'</h4>'+(r.section?'<p>Section '+esc(r.section)+'</p>':'')+(r.snippet?'<p>'+esc(r.snippet)+'</p>':'')+(r.url?'<a target="_blank" rel="noopener" href="'+esc(r.url)+'">OPEN SOURCE ↗</a>':'')+'</article>').join('')+'<p>Public-source retrieval only. Verify the current legal state and application with a qualified professional.</p>'}
async function submitAsk(e){e.preventDefault();const f=e.currentTarget,q=$('#ask-query').value.trim(),j=$('#ask-jurisdiction').value,s=$('.ask-status'),o=$('.results'),b=$('.ask-send');if(!q){s.textContent='Enter a question first.';return}b.disabled=true;s.textContent='Researching public sources…';o.innerHTML='';try{o.innerHTML=renderResults(await research(q+' in '+j));s.textContent='Research complete.'}catch(err){s.textContent=err.message||'Research could not be completed.'}finally{b.disabled=false}}
function openConsultation(){const m=document.createElement('div');m.className='modal-backdrop';m.innerHTML='<section class="modal"><button class="modal-close" aria-label="Close">×</button><div class="section-label">ACME / PROFESSIONAL CONSULTATION</div><h2>Start a matter.</h2><p>Share the essential facts. This is an intake request, not a final legal opinion.</p><form class="consult-form"><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Phone<input name="phone" type="tel"></label><label>Jurisdiction<input name="jurisdiction" placeholder="India / Maharashtra"></label><label class="full">Subject<input name="subject" required></label><label class="full">Matter summary<textarea name="summary" required></textarea></label><button class="button dark full" type="submit">Submit request →</button><p class="form-status full"></p></form></section>';document.body.append(m);document.body.classList.add('modal-open');$('.modal-close',m).onclick=()=>{m.remove();document.body.classList.remove('modal-open')};m.onclick=e=>{if(e.target===m){m.remove();document.body.classList.remove('modal-open')}};$('.consult-form',m).onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('button[type=submit]',f),s=$('.form-status',f);b.disabled=true;s.textContent='Submitting securely…';try{const r=await fetch(API+'/consultations',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(Object.fromEntries(new FormData(f)))}),x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x.error||'Submission failed.');s.textContent=x.message||'Your request has been received.';f.reset()}catch(err){s.textContent=err.message||'Submission failed.'}finally{b.disabled=false}}}
function init(){document.documentElement.classList.add('js');$('.panel-close').onclick=closeAsk;$('.ask-form').onsubmit=submitAsk;$$('[data-ask]').forEach(a=>a.onclick=e=>{e.preventDefault();openAsk(a.dataset.ask||'')});$$('[data-consult]').forEach(a=>a.onclick=openConsultation);$('.menu-toggle').onclick=()=>document.querySelector('.main-nav').classList.toggle('mobile-open');window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeAsk();$('.modal-backdrop')?.remove();document.body.classList.remove('modal-open')}})}
document.addEventListener('DOMContentLoaded',init);
